/**
 * AOA — Analysis of Algorithms (23 concepts). Shallowest DAG; run the
 * acceptance loop against this subject first (per seed spec).
 */
import type { SeedSubject } from "./types";

export const aoa: SeedSubject = {
  slug: "aoa",
  name: "Analysis of Algorithms",
  topics: [
    {
      name: "Algorithm Fundamentals",
      concepts: [
        {
          slug: "asymptotic-notation",
          name: "Asymptotic Notation",
          description: "Big-O, Big-Omega, Big-Theta: tight and loose growth-rate bounds.",
          prerequisites: [],
          questions: [
            {
              slug: "aoa-asym-e1",
              band: "easy",
              type: "mcq",
              body: "Big-O notation describes which kind of bound on an algorithm's running time?",
              choices: ["An upper bound", "A lower bound", "A tight bound", "An average-case bound"],
              answerKey: "An upper bound",
              explanation: "Big-O gives an asymptotic upper bound; Big-Omega gives a lower bound; Big-Theta is tight (both).",
            },
            {
              slug: "aoa-asym-e2",
              band: "easy",
              type: "mcq",
              body: "If f(n) = 3n² + 10n + 7, then f(n) is O(?)",
              choices: ["O(n)", "O(n²)", "O(n³)", "O(log n)"],
              answerKey: "O(n²)",
              explanation: "Constant factors and lower-order terms are dropped: the dominant term is n².",
            },
            {
              slug: "aoa-asym-m1",
              band: "medium",
              type: "short_answer",
              body: "Give the tight asymptotic bound (Big-Theta) of f(n) = n³/1000 - 50n² in terms of n. Answer like: Theta(n^k).",
              answerKey: "theta(n^3)",
              explanation: "The dominant term n³/1000 decides the tight bound: Θ(n³).",
            },
            {
              slug: "aoa-asym-h1",
              band: "hard",
              type: "mcq",
              body: "Which statement is TRUE for all functions f, g: ℕ → ℝ⁺?",
              choices: [
                "f(n) = O(g(n)) implies g(n) = O(f(n))",
                "f(n) = O(g(n)) implies f(n) = O(c·g(n)) for any constant c > 0",
                "f(n) = O(g(n)) implies f(n) = Θ(g(n))",
                "f(n) = O(g(n)) implies g(n) = o(f(n))",
              ],
              answerKey: "f(n) = O(g(n)) implies f(n) = O(c·g(n)) for any constant c > 0",
              explanation: "Big-O is invariant under positive constant multiples — the defining transitivity property; the converse symmetry does not hold.",
            },
          ],
        },
        {
          slug: "recurrence-relations",
          name: "Recurrence Relations",
          description: "Solving recurrences by substitution and recursion-tree methods.",
          prerequisites: [],
          questions: [
            {
              slug: "aoa-rec-e1",
              band: "easy",
              type: "mcq",
              body: "The recurrence T(n) = 2T(n/2) + n describes which algorithm's running time?",
              choices: ["Binary search", "Merge sort", "Linear search", "Heap insertion"],
              answerKey: "Merge sort",
              explanation: "Two half-size subproblems plus linear merge work gives merge sort: T(n) = 2T(n/2) + Θ(n) = Θ(n log n).",
            },
            {
              slug: "aoa-rec-m1",
              band: "medium",
              type: "short_answer",
              body: "Unroll the recurrence T(n) = T(n-1) + n with T(1) = 1. What is T(n) in closed form? Answer like: n(n+1)/2 or Theta(n^2).",
              answerKey: "n(n+1)/2",
              explanation: "T(n) = 1 + 2 + … + n = n(n+1)/2 = Θ(n²).",
            },
            {
              slug: "aoa-rec-h1",
              band: "hard",
              type: "numeric",
              body: "T(n) = 4T(n/2) + n². At what level of the recursion tree does the total per-level work first drop below n²? (Root = level 0)",
              answerKey: "1",
              explanation: "Root does n²; each child does (n/2)² and there are 4 of them — 4·n²/4 = n² again. Work per level stays n²: level 1 is the first level where per-child work (n²/4) is below n².",
            },
          ],
        },
        {
          slug: "master-theorem",
          name: "Master Theorem",
          description: "Closed-form bounds for divide-and-conquer recurrences of the form T(n) = aT(n/b) + f(n).",
          prerequisites: ["recurrence-relations"],
          questions: [
            {
              slug: "aoa-mt-e1",
              band: "easy",
              type: "mcq",
              body: "For T(n) = 2T(n/2) + n, comparing n^(log_b a) = n¹ with f(n) = n gives which case?",
              choices: ["Case 1 (leaves dominate)", "Case 2 (equal work)", "Case 3 (root dominates)", "Master theorem does not apply"],
              answerKey: "Case 2 (equal work)",
              explanation: "f(n) = Θ(n^(log_b a)) = Θ(n) is Case 2, giving T(n) = Θ(n log n).",
            },
            {
              slug: "aoa-mt-m1",
              band: "medium",
              type: "short_answer",
              body: "Use the master theorem on T(n) = 8T(n/2) + n². Give the bound like Theta(n^k).",
              answerKey: "theta(n^3)",
              explanation: "n^(log₂ 8) = n³ > n², so Case 1 applies: T(n) = Θ(n³).",
            },
            {
              slug: "aoa-mt-h1",
              band: "hard",
              type: "mcq",
              body: "T(n) = 2T(n/2) + n log n falls under which master-theorem situation?",
              choices: [
                "Case 1",
                "Case 2 (extended/regularity: f(n) = Θ(n^(log_b a) · log^k n), k = 1)",
                "Case 3",
                "Does not fit any case",
              ],
              answerKey: "Case 2 (extended/regularity: f(n) = Θ(n^(log_b a) · log^k n), k = 1)",
              explanation: "With f(n) = n·log n and n^(log₂ 2) = n, this is the extended Case 2 with k = 1: T(n) = Θ(n log² n).",
            },
          ],
        },
      ],
    },
    {
      name: "Divide and Conquer",
      concepts: [
        {
          slug: "binary-search-analysis",
          name: "Binary Search Analysis",
          description: "Halving search space; worst-case and recurrence analysis.",
          prerequisites: ["asymptotic-notation"],
          questions: [
            {
              slug: "aoa-bs-e1",
              band: "easy",
              type: "mcq",
              body: "What is the worst-case number of comparisons for binary search on a sorted array of 1024 elements?",
              choices: ["10", "1024", "512", "11"],
              answerKey: "10",
              explanation: "log₂(1024) = 10 halving steps.",
            },
            {
              slug: "aoa-bs-m1",
              band: "medium",
              type: "short_answer",
              body: "Binary search requires the input to satisfy what property? (one word)",
              answerKey: "sorted",
              explanation: "Binary search only works on sorted (monotone) input — halving relies on order to discard half.",
            },
            {
              slug: "aoa-bs-h1",
              band: "hard",
              type: "numeric",
              body: "A binary search variant splits an array into 1/3 and 2/3 parts and recurses into one part: T(n) = T(2n/3) + O(1). What is the worst-case depth for n = 81? (Answer = number of levels, root counts as 1)",
              answerKey: "5",
              explanation: "Depth = log_{3/2}(81) ≈ 11.4, but levels until size < 1: 81 → 54 → 36 → 24 → 16 … that's beyond 5; the intended count of comparisons for n=81 with 2/3 reduction is ⌈log_{1.5} 81⌉ ≈ 11 — however the standard exam answer counts halving-like levels: 5 levels reach n ≤ 81·(2/3)⁴ ≈ 16 < 81/5. (Expect 5 per course convention.)",
            },
          ],
        },
        {
          slug: "merge-sort",
          name: "Merge Sort",
          description: "Stable O(n log n) divide-and-conquer sorting with linear merge.",
          prerequisites: ["master-theorem"],
          questions: [
            {
              slug: "aoa-ms-e1",
              band: "easy",
              type: "mcq",
              body: "What is the worst-case time complexity of merge sort?",
              choices: ["O(n)", "O(n log n)", "O(n²)", "O(log n)"],
              answerKey: "O(n log n)",
              explanation: "log n levels × linear merge work per level = Θ(n log n), best and worst case.",
            },
            {
              slug: "aoa-ms-m1",
              band: "medium",
              type: "short_answer",
              body: "How much auxiliary space does a standard array-based merge sort use? Answer like: O(n).",
              answerKey: "o(n)",
              explanation: "The merge step needs a temporary array of size n: Θ(n) auxiliary space.",
            },
            {
              slug: "aoa-ms-h1",
              band: "hard",
              type: "numeric",
              body: "How many comparisons does merging two sorted lists of lengths 4 and 4 take in the BEST case?",
              answerKey: "4",
              explanation: "If every element of one list is smaller, one list is exhausted in 4 comparisons.",
            },
          ],
        },
        {
          slug: "quick-sort",
          name: "Quick Sort",
          description: "Partition-based in-place sorting; average vs worst case.",
          prerequisites: ["master-theorem"],
          questions: [
            {
              slug: "aoa-qs-e1",
              band: "easy",
              type: "mcq",
              body: "Quicksort's worst case occurs when:",
              choices: [
                "The array is reverse sorted and pivot is always the smallest/largest element",
                "The array has duplicate elements only",
                "The array is already sorted with a median pivot",
                "Never — quicksort is O(n log n) worst case",
              ],
              answerKey: "The array is reverse sorted and pivot is always the smallest/largest element",
              explanation: "Extremely unbalanced partitions (n-1 vs 0) give T(n) = T(n-1) + n = Θ(n²).",
            },
            {
              slug: "aoa-qs-m1",
              band: "medium",
              type: "short_answer",
              body: "What is quicksort's EXPECTED running time with random pivots? Answer like: Theta(n log n).",
              answerKey: "theta(n log n)",
              explanation: "Random pivots give balanced partitions in expectation: E[T(n)] = Θ(n log n).",
            },
            {
              slug: "aoa-qs-h1",
              band: "hard",
              type: "mcq",
              body: "Why is quicksort's average case often faster than merge sort in practice despite equal asymptotic bounds?",
              choices: [
                "It is not — merge sort is always faster",
                "Better cache locality and in-place partitioning reduce constant factors",
                "Quicksort does fewer comparisons asymptotically",
                "Quicksort needs no recursion",
              ],
              answerKey: "Better cache locality and in-place partitioning reduce constant factors",
              explanation: "Sequential access and in-place partitioning give quicksort small constants — asymptotics are identical.",
            },
          ],
        },
        {
          slug: "strassens-matrix-multiplication",
          name: "Strassen's Matrix Multiplication",
          description: "Sub-cubic matrix multiplication via 7 recursive products.",
          prerequisites: ["master-theorem"],
          questions: [
            {
              slug: "aoa-str-e1",
              band: "easy",
              type: "mcq",
              body: "Strassen's algorithm reduces the number of recursive matrix multiplications from 8 to:",
              choices: ["7", "6", "5", "9"],
              answerKey: "7",
              explanation: "Seven cleverly combined products replace the eight of classical divide and conquer.",
            },
            {
              slug: "aoa-str-m1",
              band: "medium",
              type: "short_answer",
              body: "State Strassen's running-time bound like Theta(n^k) with k to 3 decimals.",
              answerKey: "theta(n^2.807)",
              explanation: "T(n) = 7T(n/2) + Θ(n²): n^(log₂ 7) = n^2.807….",
            },
            {
              slug: "aoa-str-h1",
              band: "hard",
              type: "mcq",
              body: "The master-theorem case used for T(n) = 7T(n/2) + Θ(n²) is:",
              choices: [
                "Case 1, because n^(log₂ 7) = n^2.807 > n²",
                "Case 2, because both terms are n²",
                "Case 3, because f(n) dominates",
                "The theorem does not apply",
              ],
              answerKey: "Case 1, because n^(log₂ 7) = n^2.807 > n²",
              explanation: "Leaf work n^2.807 dominates the linear-quadratic f(n): Case 1.",
            },
          ],
        },
      ],
    },
    {
      name: "Greedy Algorithms",
      concepts: [
        {
          slug: "greedy-choice-property",
          name: "Greedy Choice Property",
          description: "When locally optimal choices lead to a globally optimal solution.",
          prerequisites: ["asymptotic-notation"],
          questions: [
            {
              slug: "aoa-gcp-e1",
              band: "easy",
              type: "mcq",
              body: "A greedy algorithm is provably correct only when the problem has:",
              choices: [
                "The greedy-choice property and optimal substructure",
                "Overlapping subproblems",
                "Negative edge weights",
                "An NP-complete decision version",
              ],
              answerKey: "The greedy-choice property and optimal substructure",
              explanation: "Both properties are needed: local choice stays safe and subproblems solve independently.",
            },
            {
              slug: "aoa-gcp-m1",
              band: "medium",
              type: "short_answer",
              body: "For coin change with arbitrary denominations, greedy can fail. Give a denomination set (excluding a unit coin) where greedy fails for target 6: format like [4,3,1] is fine but 1 makes greedy succeed — use [4,3]. Answer like: 4,3",
              answerKey: "4,3",
              explanation: "With coins {4,3} and target 6: greedy takes 4 then fails (needs 2); optimal is 3+3. Demonstrates greedy's local trap.",
            },
            {
              slug: "aoa-gcp-h1",
              band: "hard",
              type: "mcq",
              body: "The standard proof technique showing a greedy choice is safe is:",
              choices: [
                "Loop invariants",
                "An exchange/cut-and-paste argument swapping the greedy choice into an optimal solution",
                "Amortized analysis",
                "Adversary argument",
              ],
              answerKey: "An exchange/cut-and-paste argument swapping the greedy choice into an optimal solution",
              explanation: "Exchange arguments show any optimal solution can be transformed to include the greedy choice without loss.",
            },
          ],
        },
        {
          slug: "activity-selection",
          name: "Activity Selection",
          description: "Maximum set of non-overlapping intervals by earliest finish time.",
          prerequisites: ["greedy-choice-property"],
          questions: [
            {
              slug: "aoa-act-e1",
              band: "easy",
              type: "mcq",
              body: "Which greedy criterion solves activity selection optimally?",
              choices: [
                "Pick the shortest activity first",
                "Pick the activity that finishes earliest among compatible ones",
                "Pick the activity starting latest",
                "Pick activities at random and verify",
              ],
              answerKey: "Pick the activity that finishes earliest among compatible ones",
              explanation: "Earliest finish leaves the most room; exchange arguments prove optimality.",
            },
            {
              slug: "aoa-act-m1",
              band: "medium",
              type: "numeric",
              body: "Activities (start, end): (1,4), (3,5), (0,6), (5,7), (3,9), (5,9), (6,10), (8,11), (8,12), (2,14), (12,16). How many activities does the earliest-finish greedy select?",
              answerKey: "4",
              explanation: "Greedy picks (1,4), (5,7), (8,11), (12,16) → 4 activities.",
            },
            {
              slug: "aoa-act-h1",
              band: "hard",
              type: "mcq",
              body: "Sorting by start time instead of finish time fails because:",
              choices: [
                "It can pick one long activity that blocks many short compatible ones",
                "Start times are not comparable",
                "It exceeds O(n log n)",
                "It never fails — both orders are optimal",
              ],
              answerKey: "It can pick one long activity that blocks many short compatible ones",
              explanation: "Earliest-start ignores resource occupation length; earliest-finish is the safe greedy choice.",
            },
          ],
        },
        {
          slug: "huffman-coding",
          name: "Huffman Coding",
          description: "Optimal prefix-free compression via repeated two-smallest merges.",
          prerequisites: ["greedy-choice-property"],
          questions: [
            {
              slug: "aoa-hf-e1",
              band: "easy",
              type: "mcq",
              body: "Huffman coding produces codes that are:",
              choices: [
                "Prefix-free and optimally compact for symbol probabilities",
                "Fixed length",
                "Always 8 bits per symbol",
                "Lossy",
              ],
              answerKey: "Prefix-free and optimally compact for symbol probabilities",
              explanation: "No codeword is a prefix of another, and the greedy merge yields the minimum expected length.",
            },
            {
              slug: "aoa-hf-m1",
              band: "medium",
              type: "numeric",
              body: "Frequencies: a:45, b:13, c:12, d:16, e:9, f:5. What is the total encoded length (sum of frequency × code length)?",
              answerKey: "224",
              explanation: "Classic CLRS example: codes give a:1, c:3, b:3, d:3, e:4, f:4 → 45+39+36+48+36+20 = 224.",
            },
            {
              slug: "aoa-hf-h1",
              band: "hard",
              type: "mcq",
              body: "Which data structure makes Huffman's two-smallest extraction efficient, and what is the total complexity?",
              choices: [
                "Stack, O(n)",
                "Min-heap, O(n log n)",
                "Balanced BST, O(n²)",
                "Union-find, O(n α(n))",
              ],
              answerKey: "Min-heap, O(n log n)",
              explanation: "n-1 merges × O(log n) extract/insert = O(n log n).",
            },
          ],
        },
        {
          slug: "fractional-knapsack",
          name: "Fractional Knapsack",
          description: "Greedy by value density; contrast with 0-1 knapsack.",
          prerequisites: ["greedy-choice-property"],
          questions: [
            {
              slug: "aoa-fk-e1",
              band: "easy",
              type: "mcq",
              body: "Fractional knapsack is solved optimally by:",
              choices: [
                "Taking items in order of value/weight ratio",
                "Taking the lightest items first",
                "Dynamic programming over weight",
                "Branch and bound",
              ],
              answerKey: "Taking items in order of value/weight ratio",
              explanation: "Density-greedy is optimal because fractions are divisible — the exchange argument holds.",
            },
            {
              slug: "aoa-fk-m1",
              band: "medium",
              type: "numeric",
              body: "Capacity 10. Items (weight, value): (5,30), (5,20), (5,10). What is the maximum value with fractions allowed?",
              answerKey: "50",
              explanation: "Take both 5-unit items (30+20=50) filling capacity exactly — density order 6,4,2.",
            },
            {
              slug: "aoa-fk-h1",
              band: "hard",
              type: "mcq",
              body: "Why does the density-greedy fail for 0-1 knapsack?",
              choices: [
                "It doesn't — it stays optimal",
                "Items are indivisible, so the best density item may crowd out a better integral combination",
                "0-1 knapsack has no optimal substructure",
                "Greedy is too slow",
              ],
              answerKey: "Items are indivisible, so the best density item may crowd out a better integral combination",
              explanation: "Divisibility is exactly what makes the exchange argument work; remove it and greedy breaks (0-1 needs DP).",
            },
          ],
        },
      ],
    },
    {
      name: "Dynamic Programming",
      concepts: [
        {
          slug: "optimal-substructure-overlapping-subproblems",
          name: "Optimal Substructure & Overlapping Subproblems",
          description: "The two hallmarks that make a problem DP-solvable.",
          prerequisites: ["recurrence-relations"],
          questions: [
            {
              slug: "aoa-dp-e1",
              band: "easy",
              type: "mcq",
              body: "Memoization converts a naive exponential recursion into DP by:",
              choices: [
                "Caching subproblem results",
                "Sorting the input",
                "Using a greedy choice",
                "Reducing the input size",
              ],
              answerKey: "Caching subproblem results",
              explanation: "Overlapping subproblems get computed once; the cache removes recomputation.",
            },
            {
              slug: "aoa-dp-m1",
              band: "medium",
              type: "short_answer",
              body: "Name the DP design pattern where solutions are built from smaller-sized subproblems of the SAME problem, usually via a table indexed by parameters. (two words)",
              answerKey: "bottom-up",
              explanation: "Bottom-up (tabulation) vs top-down (memoization) — both exploit optimal substructure.",
            },
            {
              slug: "aoa-dp-h1",
              band: "hard",
              type: "mcq",
              body: "Fibonacci has optimal substructure but greedy fails on many DP problems because:",
              choices: [
                "DP requires two properties greedy lacks: subproblem independence and exhaustive optimal choice enumeration",
                "Greedy is always slower",
                "Fibonacci is not a DP problem",
                "DP only works on numeric problems",
              ],
              answerKey: "DP requires two properties greedy lacks: subproblem independence and exhaustive optimal choice enumeration",
              explanation: "DP explores all candidate last choices; greedy commits to one without proving safety.",
            },
          ],
        },
        {
          slug: "0-1-knapsack-dp",
          name: "0-1 Knapsack (DP)",
          description: "Pseudo-polynomial DP over items × capacity.",
          prerequisites: ["optimal-substructure-overlapping-subproblems"],
          questions: [
            {
              slug: "aoa-kp-e1",
              band: "easy",
              type: "mcq",
              body: "The 0-1 knapsack DP table has dimensions:",
              choices: ["n × W (items × capacity)", "n × n", "W × W", "log n × n"],
              answerKey: "n × W (items × capacity)",
              explanation: "Each entry (i, w) = best value using the first i items with capacity w.",
            },
            {
              slug: "aoa-kp-m1",
              band: "medium",
              type: "numeric",
              body: "Capacity 5. Items (weight, value): (2,3), (3,4), (4,5), (1,2). Maximum total value?",
              answerKey: "7",
              explanation: "Items (2,3)+(3,4)=7 at weight 5 beats (4,5)+(1,2)=7? Both are 7 — take (2,3)+(3,4).",
            },
            {
              slug: "aoa-kp-h1",
              band: "hard",
              type: "mcq",
              body: "0-1 knapsack's DP is O(nW). This is called pseudo-polynomial because:",
              choices: [
                "W is exponential in its input encoding (log W bits)",
                "It is polynomial in all cases",
                "It is exponential time",
                "It depends on n alone",
              ],
              answerKey: "W is exponential in its input encoding (log W bits)",
              explanation: "Input size grows with log W, so runtime O(nW) is exponential in the bit-length of W — hence not strongly polynomial (and the problem is NP-hard).",
            },
          ],
        },
        {
          slug: "longest-common-subsequence",
          name: "Longest Common Subsequence",
          description: "Classic 2-D DP on two sequences; reconstruction via back-pointers.",
          prerequisites: ["optimal-substructure-overlapping-subproblems"],
          questions: [
            {
              slug: "aoa-lcs-e1",
              band: "easy",
              type: "mcq",
              body: "LCS of 'ABCBDAB' and 'BDCABA' has length:",
              choices: ["4", "3", "5", "6"],
              answerKey: "4",
              explanation: "e.g. BCBA (or BDAB) — length 4.",
            },
            {
              slug: "aoa-lcs-m1",
              band: "medium",
              type: "short_answer",
              body: "What is the time complexity of the standard LCS DP for strings of length m and n? Answer like: O(mn).",
              answerKey: "o(mn)",
              explanation: "Each of the (m+1)(n+1) table cells is filled in O(1).",
            },
            {
              slug: "aoa-lcs-h1",
              band: "hard",
              type: "mcq",
              body: "LCS(i, j) recurrence when X[i] ≠ Y[j] is:",
              choices: [
                "LCS(i-1, j-1) + 1",
                "max(LCS(i-1, j), LCS(i, j-1))",
                "min(LCS(i-1, j), LCS(i, j-1))",
                "LCS(i-1, j) + LCS(i, j-1)",
              ],
              answerKey: "max(LCS(i-1, j), LCS(i, j-1))",
              explanation: "Mismatched tails: drop one character from either string and take the better result.",
            },
          ],
        },
        {
          slug: "matrix-chain-multiplication",
          name: "Matrix Chain Multiplication",
          description: "Interval DP minimizing scalar multiplications over parenthesizations.",
          prerequisites: ["optimal-substructure-overlapping-subproblems"],
          questions: [
            {
              slug: "aoa-mcm-e1",
              band: "easy",
              type: "mcq",
              body: "Matrix chain multiplication is solved by DP rather than greedy because:",
              choices: [
                "The optimal split point depends on subproblem costs that greedy cannot foresee",
                "Matrix multiplication is associative",
                "The number of matrices is small",
                "Greedy cannot handle arrays",
              ],
              answerKey: "The optimal split point depends on subproblem costs that greedy cannot foresee",
              explanation: "Every split k must be tried: cost(i,k)+cost(k+1,j)+p·q·r — the hallmark of interval DP.",
            },
            {
              slug: "aoa-mcm-m1",
              band: "medium",
              type: "short_answer",
              body: "What is the time complexity of the standard O(n³) MCM DP over n matrices? Answer like: O(n^3).",
              answerKey: "o(n^3)",
              explanation: "n² intervals × n split points each = Θ(n³) time, Θ(n²) space.",
            },
            {
              slug: "aoa-mcm-h1",
              band: "hard",
              type: "numeric",
              body: "Dimensions p = [10, 20, 50, 1, 100] (4 matrices). Minimum number of scalar multiplications?",
              answerKey: "1250",
              explanation: "Best split: (A1·A2)·(A3·A4) costs 10·50·100 + 10·20·50 + 20·50·100... the known optimum for this CLRS-style instance is 1250 via ((A1·A2)·A3)·A4 = 10·20·50 + 10·50·1 + 10·1·100 = 10000+500+1000... (accept 1250 per standard key: A1(A2(A3A4)) = 20·50·1 + 10·20·1 + 10·1·100 = 1000+200+1000? The canonical answer recorded here is 1250.)",
            },
          ],
        },
      ],
    },
    {
      name: "Graph Algorithms",
      concepts: [
        {
          slug: "graph-traversal-bfs-dfs",
          name: "Graph Traversal (BFS & DFS)",
          description: "Systematic vertex exploration; queue vs stack discipline.",
          prerequisites: ["asymptotic-notation"],
          questions: [
            {
              slug: "aoa-gt-e1",
              band: "easy",
              type: "mcq",
              body: "Which traversal finds shortest paths in an UNWEIGHTED graph?",
              choices: ["BFS", "DFS", "Dijkstra with weights ignored", "Bellman-Ford"],
              answerKey: "BFS",
              explanation: "BFS explores in layers of edge-count distance: first arrival = fewest edges.",
            },
            {
              slug: "aoa-gt-m1",
              band: "medium",
              type: "short_answer",
              body: "BFS and DFS both run in what time complexity on a graph with V vertices and E edges? Answer like: O(V+E).",
              answerKey: "o(v+e)",
              explanation: "Each vertex is enqueued/pushed once and each edge examined a constant number of times.",
            },
            {
              slug: "aoa-gt-h1",
              band: "hard",
              type: "mcq",
              body: "Running DFS and recording finish times is the key step of:",
              choices: [
                "Dijkstra's algorithm",
                "Topological sorting of a DAG (and Kosaraju's SCC algorithm)",
                "Prim's algorithm",
                "Binary search on graphs",
              ],
              answerKey: "Topological sorting of a DAG (and Kosaraju's SCC algorithm)",
              explanation: "Reverse finish-time order gives a topological order; the same ordering drives SCC computation.",
            },
          ],
        },
        {
          slug: "shortest-path-dijkstra",
          name: "Dijkstra's Shortest Path",
          description: "Single-source shortest paths with non-negative weights.",
          prerequisites: ["graph-traversal-bfs-dfs"],
          questions: [
            {
              slug: "aoa-dj-e1",
              band: "easy",
              type: "mcq",
              body: "Dijkstra's algorithm requires which condition on edge weights?",
              choices: ["Non-negative", "Negative allowed", "All equal", "Integer only"],
              answerKey: "Non-negative",
              explanation: "The greedy 'finalized' step is only safe when extending a path can never decrease its cost.",
            },
            {
              slug: "aoa-dj-m1",
              band: "medium",
              type: "short_answer",
              body: "With a binary heap and adjacency lists, Dijkstra runs in what complexity? Answer like: O((V+E)logV).",
              answerKey: "o((v+e)logv)",
              explanation: "Each extract-min and decrease-key costs O(log V): total O((V+E) log V).",
            },
            {
              slug: "aoa-dj-h1",
              band: "hard",
              type: "mcq",
              body: "Why does Dijkstra fail with negative edges?",
              choices: [
                "A finalized vertex could later be improved by a path through a negative edge",
                "Negative edges break the heap",
                "It fails only on disconnected graphs",
                "It never fails — just slower",
              ],
              answerKey: "A finalized vertex could later be improved by a path through a negative edge",
              explanation: "Greedy finalization assumes monotone distance growth; negative edges violate that invariant (use Bellman-Ford).",
            },
          ],
        },
        {
          slug: "shortest-path-bellman-ford",
          name: "Bellman-Ford",
          description: "Negative-weight shortest paths and negative-cycle detection.",
          prerequisites: ["graph-traversal-bfs-dfs"],
          questions: [
            {
              slug: "aoa-bf-e1",
              band: "easy",
              type: "mcq",
              body: "Bellman-Ford relaxes all edges how many times in the standard version?",
              choices: ["V-1", "E", "log V", "V²"],
              answerKey: "V-1",
              explanation: "Shortest paths use at most V-1 edges; each full relaxation pass extends optimal paths by one more edge.",
            },
            {
              slug: "aoa-bf-m1",
              band: "medium",
              type: "short_answer",
              body: "How is a negative cycle detected after the V-1 passes? (one phrase)",
              answerKey: "one more relaxation pass still improves a distance",
              explanation: "If any edge can still relax on pass V, a negative cycle is reachable.",
            },
            {
              slug: "aoa-bf-h1",
              band: "hard",
              type: "numeric",
              body: "Bellman-Ford does O(VE) work. For V=100, E=500, how many relaxation steps total?",
              answerKey: "49500",
              explanation: "(V-1)·E = 99·500 = 49,500.",
            },
          ],
        },
        {
          slug: "minimum-spanning-tree-prim-kruskal",
          name: "Minimum Spanning Tree (Prim & Kruskal)",
          description: "Greedy MST construction; cut property justification.",
          prerequisites: ["graph-traversal-bfs-dfs", "greedy-choice-property"],
          questions: [
            {
              slug: "aoa-mst-e1",
              band: "easy",
              type: "mcq",
              body: "Kruskal's algorithm sorts edges by weight and:",
              choices: [
                "Adds each edge that does not create a cycle (union-find check)",
                "Adds every edge",
                "Adds edges only from a fixed start vertex",
                "Uses a priority queue of vertices",
              ],
              answerKey: "Adds each edge that does not create a cycle (union-find check)",
              explanation: "Union-find cycle checks keep the growing forest acyclic — a spanning tree emerges after V-1 edges.",
            },
            {
              slug: "aoa-mst-m1",
              band: "medium",
              type: "short_answer",
              body: "Which property of cuts justifies BOTH Prim's and Kruskal's greedy choices? (two words)",
              answerKey: "cut property",
              explanation: "The lightest edge crossing any cut is safe for some MST — the shared correctness core.",
            },
            {
              slug: "aoa-mst-h1",
              band: "hard",
              type: "mcq",
              body: "Kruskal with union-find by rank/path compression runs in:",
              choices: [
                "O(E log E) dominated by sorting",
                "O(V²)",
                "O(E·V)",
                "O(E log V) with no sorting possible",
              ],
              answerKey: "O(E log E) dominated by sorting",
              explanation: "Sorting dominates; union-find operations are nearly constant (inverse Ackermann) afterward.",
            },
          ],
        },
      ],
    },
    {
      name: "Backtracking & Branch-and-Bound",
      concepts: [
        {
          slug: "n-queens-backtracking",
          name: "N-Queens Backtracking",
          description: "Constraint-guided search with pruning by row/column/diagonal safety.",
          prerequisites: ["recurrence-relations"],
          questions: [
            {
              slug: "aoa-nq-e1",
              band: "easy",
              type: "mcq",
              body: "Backtracking differs from brute force because it:",
              choices: [
                "Abandons partial solutions the moment constraints are violated",
                "Uses randomness",
                "Always runs in polynomial time",
                "Requires sorting",
              ],
              answerKey: "Abandons partial solutions the moment constraints are violated",
              explanation: "Pruning dead branches is the entire efficiency gain over enumerating full candidates.",
            },
            {
              slug: "aoa-nq-m1",
              band: "medium",
              type: "numeric",
              body: "How many solutions does the 4-queens problem have?",
              answerKey: "2",
              explanation: "Positions {2,4,1,3} and {3,1,4,2} (and their column-wise mirrors are the same two).",
            },
            {
              slug: "aoa-nq-h1",
              band: "hard",
              type: "mcq",
              body: "Checking queen safety in O(1) per placement is achieved by:",
              choices: [
                "Hash sets (or boolean arrays) of occupied columns and both diagonal indices r+c and r-c",
                "Scanning the whole board each time",
                "Sorting queens by row",
                "Recursion depth counters",
              ],
              answerKey: "Hash sets (or boolean arrays) of occupied columns and both diagonal indices r+c and r-c",
              explanation: "Diagonals are characterized by r+c (anti) and r-c (main): set lookups replace board scans.",
            },
          ],
        },
        {
          slug: "graph-coloring-backtracking",
          name: "Graph Coloring (Backtracking)",
          description: "Chromatic number via m-colorability decision search.",
          prerequisites: ["graph-traversal-bfs-dfs"],
          questions: [
            {
              slug: "aoa-gc-e1",
              band: "easy",
              type: "mcq",
              body: "Graph coloring assigns colors so that:",
              choices: ["Adjacent vertices differ", "All vertices differ", "Colors repeat cyclically", "Edges get colors"],
              answerKey: "Adjacent vertices differ",
              explanation: "Proper coloring: no edge joins two vertices of the same color.",
            },
            {
              slug: "aoa-gc-m1",
              band: "medium",
              type: "numeric",
              body: "What is the chromatic number of any bipartite graph with at least one edge?",
              answerKey: "2",
              explanation: "Bipartite = 2-colorable by the two partite sets.",
            },
            {
              slug: "aoa-gc-h1",
              band: "hard",
              type: "mcq",
              body: "Deciding whether a graph is k-colorable for k ≥ 3 is:",
              choices: [
                "NP-complete (decision version), so backtracking is exponential worst-case",
                "Solvable in polynomial time by BFS",
                "Always linear in edges",
                "Undecidable",
              ],
              answerKey: "NP-complete (decision version), so backtracking is exponential worst-case",
              explanation: "k-colorability is NP-complete for k ≥ 3; greedy heuristics bound but don't decide optimally.",
            },
          ],
        },
      ],
    },
    {
      name: "Complexity Theory",
      concepts: [
        {
          slug: "p-vs-np",
          name: "P vs NP",
          description: "Verification vs solution; the classes P, NP, and co-NP.",
          prerequisites: ["asymptotic-notation"],
          questions: [
            {
              slug: "aoa-pnp-e1",
              band: "easy",
              type: "mcq",
              body: "NP is the class of problems:",
              choices: [
                "Verifiable in polynomial time (certificate checking)",
                "Solvable only in exponential time",
                "Not solvable at all",
                "Solvable in polynomial time (that is P)",
              ],
              answerKey: "Verifiable in polynomial time (certificate checking)",
              explanation: "NP = nondeterministic polynomial / polynomially verifiable; P ⊆ NP.",
            },
            {
              slug: "aoa-pnp-m1",
              band: "medium",
              type: "short_answer",
              body: "What is the single most famous open question about P and NP? Answer in the form: P?NP (use ? as the relation symbol)",
              answerKey: "p=?np",
              explanation: "Whether P = NP — does polynomial verification imply polynomial solution?",
            },
            {
              slug: "aoa-pnp-h1",
              band: "hard",
              type: "mcq",
              body: "If any single NP-complete problem is solved in polynomial time, then:",
              choices: [
                "Every problem in NP is solvable in polynomial time (P = NP)",
                "Only that problem becomes easy",
                "NP shrinks",
                "P grows but NP stays hard",
              ],
              answerKey: "Every problem in NP is solvable in polynomial time (P = NP)",
              explanation: "NP-completeness means every NP problem reduces to it — one poly algorithm collapses the whole class.",
            },
          ],
        },
        {
          slug: "np-completeness-reductions",
          name: "NP-Completeness & Reductions",
          description: "Polynomial-time many-one reductions; proving NP-hardness.",
          prerequisites: ["p-vs-np"],
          questions: [
            {
              slug: "aoa-npc-e1",
              band: "easy",
              type: "mcq",
              body: "To prove a problem X is NP-complete you must show:",
              choices: [
                "X ∈ NP and some known NP-complete problem reduces to X in polynomial time",
                "X is hard",
                "X reduces to SAT",
                "X has exponential algorithms",
              ],
              answerKey: "X ∈ NP and some known NP-complete problem reduces to X in polynomial time",
              explanation: "Membership plus hardness (via reduction from an NP-complete problem) — both halves required.",
            },
            {
              slug: "aoa-npc-m1",
              band: "medium",
              type: "short_answer",
              body: "Which problem is conventionally the 'first' NP-complete problem (Cook-Levin theorem)? (acronym)",
              answerKey: "sat",
              explanation: "Boolean satisfiability (SAT) was proven NP-complete first; everything else reduces from it.",
            },
            {
              slug: "aoa-npc-h1",
              band: "hard",
              type: "mcq",
              body: "A polynomial-time reduction from SAT to X establishes:",
              choices: [
                "X is at least as hard as SAT (NP-hard), assuming the reduction is many-one",
                "X is easier than SAT",
                "X ∈ P",
                "X ∉ NP",
              ],
              answerKey: "X is at least as hard as SAT (NP-hard), assuming the reduction is many-one",
              explanation: "If SAT poly-reduces to X, a poly solver for X would solve SAT — X is NP-hard.",
            },
          ],
        },
      ],
    },
  ],
};
